apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-limitmemory
  namespace: default
  annotations:
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-6 Resource Availability
    policy.open-cluster-management.io/standards: NIST SP 800-53
  creationTimestamp: 2024-09-26T08:07:28Z
  generation: 4
  managedFields:
    - apiVersion: policy.open-cluster-management.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:policy.open-cluster-management.io/categories: {}
            f:policy.open-cluster-management.io/controls: {}
            f:policy.open-cluster-management.io/standards: {}
        f:spec:
          .: {}
          f:disabled: {}
          f:policy-templates: {}
          f:remediationAction: {}
      manager: unknown
      operation: Update
      time: 2024-09-28T10:08:07Z
    - apiVersion: policy.open-cluster-management.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:compliant: {}
          f:placement: {}
          f:status: {}
      manager: governance-policy-propagator
      operation: Update
      subresource: status
      time: 2024-10-03T11:25:41Z
  resourceVersion: "3976265"
  uid: 63732b6a-8efa-4a79-9fd9-0f276b4db88c
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-limitrange-example
        spec:
          namespaceSelector:
            include:
              - cbdc-app
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: v1
                kind: LimitRange
                metadata:
                  name: mem-limit-range
                spec:
                  limits:
                    - default:
                        memory: 512Mi
                      defaultRequest:
                        memory: 256Mi
                      type: Container
          remediationAction: inform
          severity: medium
  remediationAction: enforce
status:
  compliant: Compliant
  placement:
    - placement: bank-policy-set-placement
      placementBinding: bank-policy-set-placement
      policySet: bank-policy-set
    - placement: policy-limitmemory-placement
      placementBinding: policy-limitmemory-placement
  status:
    - clustername: prod
      clusternamespace: prod
      compliant: Compliant
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policy-limitmemory-placement
  namespace: default
  creationTimestamp: 2024-09-26T08:07:28Z
  generation: 1
  resourceVersion: "3976266"
  uid: c1515df6-72f4-4a92-8b71-d91cd13ea511
spec:
  clusterSets: []
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - uat
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
status:
  conditions:
    - lastTransitionTime: 2024-09-26T08:07:28Z
      message: Placement configurations check pass
      reason: Succeedconfigured
      status: "False"
      type: PlacementMisconfigured
    - lastTransitionTime: 2024-10-03T11:25:41Z
      message: No ManagedCluster matches any of the cluster predicate
      reason: NoManagedClusterMatched
      status: "False"
      type: PlacementSatisfied
  decisionGroups:
    - clusterCount: 0
      decisionGroupIndex: 0
      decisionGroupName: ""
      decisions:
        - policy-limitmemory-placement-decision-1
  numberOfSelectedClusters: 0
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-limitmemory-placement
  namespace: default
  creationTimestamp: 2024-09-26T08:07:29Z
  generation: 1
  resourceVersion: "2693169"
  uid: f6be6869-49c6-4bad-a19e-041bd7028733
placementRef:
  name: policy-limitmemory-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-limitmemory
    apiGroup: policy.open-cluster-management.io
    kind: Policy
